public enum CustomerType {
	KID_1,
	KID_2,
	ADULT_BARMAID,
	ADULT_BARTENDER,
	ADULT_BLACKSMITH,
	ADULT_FARMER,
	ADULT_FISHERMAN,
	WIZARD_BLUE,
	WIZARD_GREEN,
	WIZARD_YELLOW,
	WIZARD_PURPLE,
	MERCHANT_BLUE,
	MERCHANT_GREEN,
	MERCHANT_PURPLE,
	MERCHANT_GOLD,
	KING
}